spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
  tomcat:
    max-wait: 2000
    max-active: 50
    max-ide: 20
    min-ide: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000

UserController:
  signin: Authenticates user and returns its JWT token
  signup: Create user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
